# Site Settings
name: Teachableverse
title: Teachableverse | Make own Metaverse
description: Teachableverse is a platform that allows users to build on their own metaverse using AI.
tags:
  - metaverse
  - AI
  - teachablemachine
  - game
  - gym
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: teachableverse@gmail.com
# See: https://disqus.com/
disqus_username: teachableverse
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: xnqwnnnb

# Social Media Settings
# Remove the item if you don't need it
github_username: teachableverse
facebook_username: teachableverse
twitter_username: teachableverse
instagram_username: teachableverse
linkedin_username: teachableverse
medium_username: teachableverse


# Posts Settings
show_time_bar: true
show_modal_on_exit: false
show_modal_on_finish_post: true
two_columns_layout: true


# Advanced Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.teachableverse.com" # the base hostname & protocol for your site
google_analytics: "G-8G0GJQ0C1Q"
language: "en"
categories_folder: category
sent_message_url: "/contact/message-sent/"


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: true
use_logo: false

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content

# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]

# Theme
version: v0.1.0
